name: 'Create Deployment'
description: 'Create a GitHub deployment'
author: 'Jack WIckham'
inputs:
  token:
    required: true
    description: 'GitHub token to use to create the deployment'
runs:
  using: 'node12'
  main: 'dist/index.js'
